language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script:
  - composer install -n --no-interaction
  - php bin/console assets:install web --symlink
  - php bin/console assetic:dump
script:
  - phpunit --debug -vc app/ --coverage-clover build/logs/clover.xml