language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script:
  - composer install -n --no-interaction
  - php app/console assets:install web --symlink
  - php app/console assetic:dump
script:
  - phpunit -c app/ --coverage-clover build/logs/clover.xml