language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
matrix:
  include:
    - php: 5.4
      env: CODECLIMATE=1
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - composer self-update
  - composer install -n --no-interaction
  - php app/console assets:install web --symlink
  - php app/console assetic:dump
script:
  - app/console doctrine:schema:update --force
  - phpunit -c app/ --coverage-clover build/logs/clover.xml
  - if [ "$CODECLIMATE" = "1" ]; then ./vendor/codeclimate/php-test-reporter/composer/bin/test-reporter; else echo "Not submitting to codeclimate this time"; fi